### ISSUE TITLE
Subtotal increase after cart.html page refresh

### ISSUE THREAD

**Issue by na86** [bigcartel/dugway#146]
Hi, i'm building a theme with Dugway. 
I've noticed that my product cart subtotal increase at every page refresh! 
Any help? 

thanks guys! 

Na86

**Comment by nickendle** [comment]
@na86 Are you refreshing the page immediately after adding a product to your cart? Perhaps the POST request is being re-submitted on each refresh, causing the product quantity to be increased?

Otherwise if you have any code that's modifying the display of `cart.total` or `cart.subtotal` you may want to check that.
